CREATE TABLE "user" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "email" varchar UNIQUE,
  "password" varchar
);

CREATE TABLE "chat" (
  "chat_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_name" varchar,
  "is_private" BOOLEAN
);

CREATE TABLE "member" (
  "id" SERIAL PRIMARY KEY,
  "user_id" integer,
  "chat_id" integer,
  "joined_date" timestamp,
  "left_datetime" timestamp,
  "username" varchar
);

CREATE TABLE "message" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "from" integer,
  "message_text" text,
  "sent" timestamp,
  "chat_id" int
);

ALTER TABLE "message" ADD FOREIGN KEY ("from") REFERENCES "user" ("user_id");

ALTER TABLE "member" ADD FOREIGN KEY ("chat_id") REFERENCES "chat" ("chat_id");

ALTER TABLE "message" ADD FOREIGN KEY ("chat_id") REFERENCES "chat" ("chat_id");

ALTER TABLE "member" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("user_id");
