CREATE TABLE "user" (
  "userId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "email" varchar UNIQUE,
  "password" varchar
);

CREATE TABLE "chat" (
  "chat_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_name" varchar,
  "type" char
);

CREATE TABLE "member" (
  "id" SERIAL PRIMARY KEY,
  "userId" integer,
  "chat_id" integer,
  "joined_date" timestamp,
  "left_datetime" timestamp,
  "username" varchar
);

CREATE TABLE "message" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "from" integer,
  "message_text" text,
  "sent" timestamp,
  "chat_id" int
);

ALTER TABLE "message" ADD FOREIGN KEY ("from") REFERENCES "user" ("userId");

ALTER TABLE "member" ADD FOREIGN KEY ("chat_id") REFERENCES "chat" ("chat_id");

ALTER TABLE "message" ADD FOREIGN KEY ("chat_id") REFERENCES "chat" ("chat_id");

ALTER TABLE "member" ADD FOREIGN KEY ("userId") REFERENCES "user" ("userId");
